version: '3.1'
services:
  mysqldb:
    image: mysql:5.6
    container_name: backpackerdb
    restart: always
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buses
      MYSQL_PASSWORD: root

  springboot:
    build: .
    restart: always
    container_name: backpackerapi
    ports:
      - 8080:8080
    #working_dir: /app
    depends_on:
      - mysqldb
